### ISSUE TITLE
setup error line 16?

### ISSUE THREAD

**Issue by filmcup** [mchwalisz/thingspeak#12]
i got some error in setup. change "with open(path.join(here, 'thingspeak', '__init__.py'), 'r') as fd:" in line 14 to "with open(path.join(here, 'thingspeak', '__init__.py'), encoding='utf-8') as fd:" and work fine.

D:\>pip install thingspeak==0.3.6
Collecting thingspeak==0.3.6
  Downloading thingspeak-0.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-build-ogbv7cho\thingspeak\se
tup.py", line 16, in <module>
        fd.read(), re.MULTILINE).group(1)
      File "C:\ProgramData\Anaconda3\lib\encodings\cp874.py", line 23, in decode

        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x82 in position 93: c
haracter maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\
AppData\Local\Temp\pip-build-ogbv7cho\thingspeak\

**Comment by mchwalisz** [comment]
It will however not solve the problem for old version you are trying to use.
